version: '2'

services:
  web:
    image: jenkins/jenkins:lts
    ports:
     - "5000:5000"
     - "9091:8080"
    user: root
    command: bash -c "apt update && apt -y install python-pip & java -jar /usr/share/jenkins/jenkins.war"
    restart: always
    volumes:
     - ${PWD}/jenkins_container_data:/var/jenkins_home
